name: Metrics
on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          user: averyanalex
          template: classic
          base: header, activity, community, repositories
          config_animations: yes
          config_timezone: Europe/Moscow
          optimize: no
          use_prebuilt_image: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: percentage

          plugin_lines: yes

          plugin_repositories: yes
          plugin_repositories_featured: averyanalex/quantpiler

          plugin_traffic: yes
